
.. _DMRITOOL: http://dmritool.readthedocs.org/en/latest/index.html 
.. _`DMRITOOL doxygen documentation`: http://diffusionmritool.github.io/dmritool_doxygen
.. _`dmritool-discussion`:  http://www.nitrc.org/mailman/listinfo/dmritool-discussion

.. Licenses
.. _GPL: http://www.gnu.org/licenses/gpl.html

.. Organizations
.. _`Section on Tissue Biophysics and Biomimetics (STBB)`: http://stbb.nichd.nih.gov/index.html
.. _`National Institutes of Health`: http://www.nih.gov/
.. _`Athena project team`: https://team.inria.fr/athena/
.. _INRIA: https:/inria.fr/
.. _`Brainnetome center`: http://www.brainnetome.org/en/
.. _`Institute of Automation, Chinese Academy of Sciences`: http://english.ia.cas.cn/
.. _`MIND Lab`: http://www.unc.edu/~ptyap/index.html
.. _`IDEA Group`: https://www.med.unc.edu/bric/ideagroup
.. _`University of North Carolina at Chapel Hill`: http://www.unc.edu/

.. Tools
.. _matlab: http://www.mathworks.com
.. _GCC: https://gcc.gnu.org/
.. _Git: http://git-scm.com/
.. _SVN: https://subversion.apache.org/
.. _VTK: http://www.vtk.org/
.. _`Visualization Toolkit`: http://www.vtk.org/
.. _ITK: http://www.itk.org/
.. _`Insight Toolkit`: http://www.itk.org/
.. _GSL: http://www.gnu.org/software/gsl/
.. _`GNU Scientific Library`: http://www.gnu.org/software/gsl/
.. _spams: http://spams-devel.gforge.inria.fr
.. _CMake: http://www.cmake.org
.. _SlicerExecutionModel: https://github.com/Slicer/SlicerExecutionModel
.. _MKL: https://software.intel.com/en-us/intel-mkl
.. _OpenBLAS: https://github.com/xianyi/OpenBLAS
.. _Lapack: https://www.netlib.org/lapack/
.. _Qt: http://www.qt-project.org
.. _GTest: https://code.google.com/p/googletest/
.. _vtkviewer:  https://github.com/HalCanary/vtkviewer
.. _nifti: http://nifti.nimh.nih.gov/nifti-1/
.. _niftilib: sourceforge.net/projects/niftilib
.. _nrrd: http://teem.sourceforge.net/nrrd/index.html
.. _Doxygen: http://www.doxygen.org
.. _OpenMP: http://openmp.org/wp/

.. software
.. _FSL: http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/
.. _CAMINO: http://cmic.cs.ucl.ac.uk/camino/
.. _paraview: http://www.paraview.org/


.. vim:syntax=rst
